export enum MultipleTabsActionTypes {
  FETCH_USERS = '[MULTIPLE_TABS]=_FETCH_USERS',
  CLEAR_USERS = '[MULTIPLE_TABS]_CLEAR_USERS',
  FETCH_GROUPS = '[MULTIPLE_TABS]_FETCH_GROUPS',
  CLEAR_GROUPS = '[MULTIPLE_TABS]_CLEAR_GROUPS',
  FETCH_PHONES = '[MULTIPLE_TABS]_FETCH_PHONES',
  CLEAR_PHONES = '[MULTIPLE_TABS]_CLEAR_PHONES',
}
